// Auto-generated file. Do not edit directly.
window.BLOG_POSTS_DATA = [
  {
    "filename": "docker.md",
    "content": "---\ntitle: \"CONTAINERIZING STACKS\"\ndate: \"2026-03-30\"\nsummary: \"Setting up multi-stage alpine builds for rust and node microservices...\"\nthumbnail: \"images/lod_planets.png\"\n---\n# Containerizing stacks\n\nTo deploy retro software or modern microservices reliably, we use Docker. This log discusses optimizing size using multi-stage builds.\n\n## Multi-Stage Concept\n\nInstead of shipping compiler toolchains inside the final runner image, we separate the build stage from the execution stage. This keeps production images incredibly small and secure.\n\nHere is a standard example for a Rust microservice:\n\n```dockerfile\n# Stage 1: Build binary\nFROM rust:1.80-alpine AS builder\nRUN apk add --no-cache musl-dev\nWORKDIR /app\nCOPY . .\nRUN cargo build --release\n\n# Stage 2: Minimal runner\nFROM alpine:3.18\nWORKDIR /app\nCOPY --from=builder /app/target/release/microservice .\nCMD [\"./microservice\"]\n```\n\nUsing this approach, the final runtime container is reduced from over `1.5 GB` down to just `15 MB`!\n"
  },
  {
    "filename": "nbody.md",
    "content": "---\ntitle: \"N-BODY GRAVITY SIMULATION\"\ndate: \"2026-04-28\"\nsummary: \"Writing custom Euler integration methods for multi-body orbital tracks...\"\nthumbnail: \"images/nbody_simulation.png\"\n---\n# N-Body Gravity Simulation\n\nSimulating gravitational interactions between multiple astronomical bodies (like stars and planets) is a classic problem in computational physics. This post covers the mathematical and algorithmic design behind our `NBSS.EXE` python simulation.\n\n## Newtonian Mechanics\n\nFor any body $i$, the net gravitational force exerted by all other bodies $j$ is calculated as:\n\n$$\\vec{F}_i = G m_i \\sum_{j \\neq i} \\frac{m_j (\\vec{r}_j - \\vec{r}_i)}{|\\vec{r}_j - \\vec{r}_i|^3}$$\n\nTo resolve acceleration and update positions, we can use numerical integration methods such as Euler-Cromer or Verlet.\n\n## Code Design\n\nHere is a look at the core integration loop implemented in Python:\n\n```python\ndef update_bodies(bodies, dt):\n    # Compute force vectors\n    forces = [np.zeros(3) for _ in bodies]\n    for i, b1 in enumerate(bodies):\n        for j, b2 in enumerate(bodies):\n            if i == j: continue\n            diff = b2.pos - b1.pos\n            dist = np.linalg.norm(diff)\n            # Softening factor to avoid infinity at close range\n            force_mag = G * b1.mass * b2.mass / (dist**2 + softening**2)\n            forces[i] += force_mag * (diff / dist)\n            \n    # Update velocities and positions\n    for i, b in enumerate(bodies):\n        accel = forces[i] / b.mass\n        b.vel += accel * dt\n        b.pos += b.vel * dt\n```\n\n## Performance Scaling\n\n![N-Body simulation screen](images/nbody_simulation.png)\n\nUsing naive $O(N^2)$ direct computation, the simulation handles up to a few thousand bodies in real-time. For higher counts, we can optimize by employing a **Barnes-Hut octree** which reduces complexity to $O(N \\log N)$.\n"
  },
  {
    "filename": "planets.md",
    "content": "---\ntitle: \"PRODUCING PLANETS IN C#\"\ndate: \"2026-05-18\"\nsummary: \"Optimizing Level of Detail (LOD) planet meshes with octrees in Unity...\"\nthumbnail: \"images/lod_planets.png\"\n---\n# Producing Planets in C#\n\nGenerating realistic planetary bodies in real-time requires smart data structures and procedural generation techniques. This post covers the design of an **Octree-based Level of Detail (LOD)** system implemented in Unity.\n\n## Core Architecture\n\nTo render massive planets without exhausting GPU memory, we divide the planet's sphere into 6 quadtree faces (forming a cube map), and project them onto a sphere. As the camera gets closer:\n1. We subdivide the quadtree nodes.\n2. We request new noise heights for vertices.\n3. We generate high-res mesh chunks on background worker threads.\n\nHere is a simplified C# snippet demonstrating subdivision checking:\n\n```csharp\npublic void UpdateNode(Vector3 cameraPosition) {\n    float distance = Vector3.Distance(cameraPosition, center);\n    if (distance < subdivideDistance && depth < maxDepth) {\n        Subdivide();\n    } else if (distance > collapseDistance && isSubdivided) {\n        Collapse();\n    }\n}\n```\n\n## Visualizing Heightfields\n\nWe use a layered 3D Perlin and simplex noise pipeline to generate realistic continents, mountains, and ocean trenches.\n\n![LOD Planet Generation Example](images/lod_planets.png)\n\nThis mesh calculation is offloaded to jobs using the C# Job System, compiling down to highly optimized native code with Burst Compiler.\n"
  },
  {
    "filename": "rust.md",
    "content": "---\ntitle: \"MEMORY SAFETY DEMYSTIFIED\"\ndate: \"2026-03-12\"\nsummary: \"A deep dive into the borrow checker, lifetimes, and smart pointers...\"\nthumbnail: \"images/nbody_simulation.png\"\n---\n# Memory Safety Demystified\n\nRust provides memory safety guarantees without needing a garbage collector. This post explores the compiler mechanisms that make this possible.\n\n## The Borrow Checker\n\nThe Rust compiler enforces strict ownership rules:\n1. Every value has a single owner variable.\n2. You can have any number of immutable references (`&T`) OR exactly one mutable reference (`&mut T`) at any given time.\n3. References must always remain valid (cannot outlive the owner).\n\n```rust\nfn main() {\n    let mut data = vec![1, 2, 3];\n    let ref1 = &data; // Ok\n    let ref2 = &data; // Ok\n    // let ref_mut = &mut data; // ERROR: cannot borrow as mutable\n    println!(\"{:?}, {:?}\", ref1, ref2);\n}\n```\n\nBy verifying these constraints at compile-time, Rust prevents common bugs like dangling pointers, data races, and double-free vulnerabilities!\n"
  },
  {
    "filename": "shaders.md",
    "content": "---\ntitle: \"EXPLORING SHADER GRAPH\"\ndate: \"2026-05-10\"\nsummary: \"Custom vertex displacement shaders for fluid water surfaces...\"\nthumbnail: \"images/physics_vehicles.png\"\n---\n# Exploring Shader Graph\n\nProcedural styling is a cornerstone of retro and modern games alike. This post details how to implement vertex displacement to simulate realistic water ripples using Unity's Shader Graph or raw HLSL.\n\n## Vertex Displacement Formula\n\nTo simulate fluid wave dynamics, we displace the vertex position along its normal using a combination of sine waves:\n\n$$y = A \\sin(k \\cdot x - \\omega \\cdot t)$$\n\nWhere:\n- $A$ is the amplitude\n- $k$ is the wave number (spatial frequency)\n- $\\omega$ is the angular frequency (speed)\n\n## Implementation Steps\n\n1. **Create the Time Node**: Connect it to a multiply node to control wave speed.\n2. **Combine Noise Layers**: Combine a tiling gradient noise with simple sine waves to add complexity.\n3. **Displace Vertices**: Multiply the noise output by the vertex normal vector and add it to the position.\n\n![Shader Graph Demo](images/physics_vehicles.png)\n\nThis visual effect brings flat plane geometry to life, creating interactive environments with minimal performance overhead.\n"
  },
  {
    "filename": "ui.md",
    "content": "---\ntitle: \"RETRO OS WEB DESIGN\"\ndate: \"2026-04-15\"\nsummary: \"How to style classic DOS/Win16-like interfaces using modern CSS grid...\"\nthumbnail: \"images/player_controller.png\"\n---\n# Retro OS Web Design\n\nBringing nostalgic styles from the 80s and 90s to the web is a fun exercise in CSS control. This post discusses the styling tokens and design principles used to construct `PORTFOLIO.EXE`.\n\n## Design Rules\n\n1. **Monospace Typography**: Always use pixelated/monospaced fonts like *Press Start 2P* or standard Courier.\n2. **Beveled Borders**: Emulate old windows by using heavy borders with varying colors to represent lighting (e.g. gold, yellow, and dark lines).\n3. **Strict Grid Layouts**: Retro interfaces relied on strict grids and window regions rather than flowing flexboxes. Using CSS grid helps maintain this rigidity.\n\n```css\n.frame {\n  display: grid;\n  grid-template-rows: auto 1fr auto;\n  border: 6px solid var(--gold);\n}\n```\n\n## Creating Retro Elements\n\nUsing custom linear gradients, we can emulate CRT monitor scanlines:\n\n```css\nbody::after {\n  content: '';\n  position: fixed;\n  inset: 0;\n  background: repeating-linear-gradient(\n    0deg, transparent, transparent 2px,\n    rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px\n  );\n  pointer-events: none;\n}\n```\n\nThis simple overlay gives the webpage a CRT glow that completes the retro desktop visual experience!\n"
  }
];
